name: Build Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          pip install hatchling
          pip install -e .
          pip install pyinstaller
          
      - name: Build Binary
        run: pyinstaller --onefile --name smartman smartman/cli.py
        
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/smartman*
